'''
Model-generated precipitation data may need to be adjusted based on elevation. This script uses elevation values within
the catchment area to compute median elevation. The elevation values of the full WaSiM domain would be available
in the "elevations.dhm" file generated by TANALYS.

'''
#import libraries
import numpy as np
import os
import rasterio

#get and set path of working directory
path = os.getcwd() 

#set directory paths and filenames
#path to the WaSiM input folder
WaSiM_input_folder = 'inputfolderpath'
#filename for the elevation grid
elevation_file = 'elevation.dhm'
#filename for the subcatchment identification file
subcatchment_identification_file = 'subcatchments.ezg'

##############################################################################################################################################################################
def generate_elevation_correction_raster(input_folder, subcatchment_identification_file, elevation_file):

    #open subcatchment identification raster
    subcatchments_ds = rasterio.open(os.path.join(input_folder, subcatchment_identification_file))
    subcatchments = subcatchments_ds.read(1)
    #make copy for further calculations and set data values to 0
    subcatchments_zeroed = subcatchments.copy()
    subcatchments_zeroed[subcatchments_zeroed > 0] = 0
    
    #subcatchments_calculation = subcatchments.copy()
    #subcatchments_calculation[subcatchments_calculation > 0] = 0

    #load elevation identification raster
    elevations_ds = rasterio.open(os.path.join(input_folder, elevation_file))
    elevations = elevations_ds.read(1)
    #make copy for further calculations and set data values to 0
    #elevations_calculation = elevations.copy()
    #elevations_calculation[elevations_calculation > 0] = 0    
    
    #create new elevations raster with data values limited to catchment area
    elevations_catchment = elevations.copy()
    elevations_catchment = elevations_catchment + subcatchments_zeroed
    elevations_catchment[elevations_catchment < 0] = -9999
    
    #make a copy to calculate median elevation
    elevations_catchment_calculation = elevations_catchment.copy()
    elevations_catchment_calculation[elevations_catchment_calculation == -9999] = 'nan'
    median_elevation = round(np.nanpercentile(elevations_catchment_calculation, 50), 2)
    
    #make another copy for calculating correction factors
    elevation_correction = elevations_catchment.copy()
    #from regression: N% precipitation change for Xm change in elevation
    elevation_correction[:,:] = 1 + (N/100)*(elevations_catchment[:,:] - median_elevation)/(X)
    #set no data cells to -9999
    elevation_correction[elevation_correction < 0] = -9999
    
    #median and average of elevation correction factors
    elevation_correction_calculation = elevation_correction.copy()
    elevation_correction_calculation[elevation_correction_calculation == -9999] = 'nan'
    correction_median = round(np.nanpercentile(elevation_correction_calculation, 50), 2)
    correction_mean = round(np.nanmean(elevation_correction_calculation, 2)
    
    #profiles and writing rasters
    #profiles of dhm and ezg rasters
    kwds_elevations = elevations_ds.profile
    kwds_subcatchments = subcatchments_ds.profile
    
    #correction grids are needed for each month by WaSiM
    for file_extension in ('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12')
        elevation_correction_file = rasterio.open(os.path.join(input_folder, 'elevation_correction_grid.' + file_extension), mode = 'w', **kwds_elevations)
        elevation_correction_file.write(elevation_correction, 1)
        elevation_correction_file.close()
        
    #close rasters
    subcatchments_ds.close()
    elevations_ds.close()
    
    #print median and mean correction factors
    print("median correction factor is:" + correction_median)
    print("mean correction factor is:" + correction_mean)
    
    #end function
##############################################################################################################################################################################    
   
#run function
generate_elevation_correction_raster(input_folder, elevation_file, subcatchment_identification_file)
